name: Publish VS Code Extension

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint || echo "No lint script found"

      - name: Run tests
        run: npm test || echo "No test script found"

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install specific vsce version
        run: npm install -g @vscode/vsce@3.3.2

      - name: Publish with explicit version
        run: |
          # Get version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Publish with explicit version
          vsce publish $CURRENT_VERSION -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
